name: Movizz CI

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
        # run: | 
        #   ls
        #   mkdir test
        #   cd test 
        #   touch index.html
        
      name: Clone Github Repository
      uses: actions/checkout@v4

    -
      name: Install Dependencies
      run: |
        cd code/server
        npm ci
        