name: Movizz CI

on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # -
        # run: | 
        #   ls
        #   mkdir test
        #   cd test 
        #   touch index.html
    -   
      name: Clone Github Repository
      uses: actions/checkout@v4

    -
      name: Install Dependencies
      run: |
        cd code/server
        npm ci
        echo "Dependencies installed successfully"
    -
        name: Install Dependencies
        run: |
            cd code/client
            npm ci
            echo "Dependencies installed successfully"
        
    -
      name: Compile Server Files
      run: |
        cd code/server
        npm run compile
        echo "Tests executed successfully"

    
    -
      name: Compile Client Files
      run: |
        cd code/client
        npm run build
        echo "Tests executed successfully"

    -
      name: Install test databases
      run: | 
        sudo service mysql start
        cd code/server/mysql
        mysql -uroot -proot -e 'SOURCE script.test.sql,'
        mysql -uroot -proot -e 'SHOW DATABASES,'
        echo "Test databases installed successfully"

    # -